branch-defaults:
  master:
    environment: rmg-env-cloned-2
environment-defaults:
  rmg-env-cloned-2:
    branch: null
    repository: null
global:
  application_name: rmg
  default_ec2_keyname: rmg-prod-east
  default_platform: PHP 8.2 running on 64bit Amazon Linux 2023/4.1.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
